### ISSUE TITLE
[Bug]: HtmlView designated initializer should be public for subclassing after 14.0.0

### ISSUE THREAD

**Issue by mathewlee83** [braze-inc/braze-swift-sdk#183]
### Platform

iOS

### Platform Version

iOS 26.1

### Braze SDK Version

14.0.0

### Xcode Version

Xcode 26.1.1

### Computer Processor

Apple (M1)

### Repro Rate

100% 

### Steps To Reproduce

1. Create a subclass of `HtmlView`:wift
class CustomHTMLView: HtmlView {
    init(message: Braze.InAppMessage.Html, customParam: String) {
        super.init(message: message, attributes: .defaults)
    }
}

### Expected Behavior

The subclass should be able to call the parent's designated initializer, allowing custom initialization logic in subclasses.

### Actual Incorrect Behavior

Compilation error occurs because the designated initializer is `internal` and not accessible from subclasses in different modules:

### Verbose Logs

```shell

```

### Additional Information

This worked in BrazeUI 13.0.0 but broke in 14.0.0 when the designated initializer was changed to internal.

**Proposed Solution:**
Make the designated initializer `public` and provide a default value for the `persistence` parameter:

public init(
    message: Braze.InAppMessage.Html,
    attributes: Attributes = .defaults,
    presented: Bool = false,
    persistence: InAppMessagePersistenceProtocol = InAppMessagePersistenceQueueWriter()
) {
    // ...
}
