### ISSUE TITLE
[Bug]: Build failed

### ISSUE THREAD

**Issue by sergey-shablenko** [braze-inc/braze-swift-sdk#133]
### Platform

iOS

### Platform Version

IOS 14

### Braze SDK Version

9.0.0

### Xcode Version

15.01

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

podfile has following

platform :ios, '14'

use_frameworks! :linkage => :static

pod 'BrazeKit'
pod 'BrazeUI'

### Expected Behavior

App builds

### Actual Incorrect Behavior

App does not build in github macos-14-xlarge runner

Undefined symbols for architecture arm64:
Error:   "_$s11ActivityKit0A0C23pushToStartTokenUpdatesAC04PushfG0Vyx_GvgZ", referenced from:
Warning:       _$s8BrazeKit0A0C14LiveActivitiesC19registerPushToStart7forType4nameScTyyts5NeverOG08ActivityB00M0CyxGm_SStAL0M10AttributesRzAA0acmN0RzlFyyYaYbcfU0_TY0_ in BrazeKit(BrazeKit-arm64-master.o)
Error: ld: symbol(s) not found for architecture arm64
Error: clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Additional Information

Build from my laptop works just fine, which is confusing as Im running build on M2 Macos 14.5 xcode 15.4 which is not that different from github runner

- braze-react-native-sdk (11.0.0):
    - BrazeKit (~> 9.0.0)
    - BrazeLocation (~> 9.0.0)
    - BrazeUI (~> 9.0.0)
    - glog
    - RCT-Folly (= 2022.05.16.00)
    - React-Core
  - BrazeKit (9.0.0)
  - BrazeLocation (9.0.0):
    - BrazeKit (= 9.0.0)
  - BrazeUI (9.0.0):
    - BrazeKit (= 9.0.0)

**Comment by cleberada** [comment]
@sergey-shablenko Could you solved it?

**Comment by jerielng** [comment]
@cleberada If you are facing similar build issues, please send in your project and configuration details (i.e. Xcode versions, OS versions, which version of the Braze SDK you are using, etc.) to support@braze.com with any relevant build logs that reproduce this scenario so that our support team can assist you. Thanks!

**Comment by cleberada** [comment]
@jerielng Thank you. I've already sent the email to support, and I'm waiting for a response. But we can also include the resolution in this thread to help other people in the future.
